Name : Isbin Shrestha



Student ID : 2358106


Group : 19

 Task- 1:
 Create a Python program that converts between different units of measurement.


In [ ]:
def convert_units(conversion_type, direction, value):
    """
    Convert between different units of measurement.

    Args:
        conversion_type (str): Type of conversion (length/weight/volume)
        direction (str): Conversion direction ('1' or '2')
        value (float): Numeric value to convert

    Returns:
        str: Formatted conversion result with units

    Raises:
        ValueError: If invalid conversion_type or direction is provided
    """
    # Conversion factors
    meters_to_feet = 3.28084
    kg_to_pounds = 2.20462
    liters_to_gallons = 0.264172

    if conversion_type == "length":
        if direction == "1":
            result = value * meters_to_feet
            return f"{value} meters = {result:.2f} feet"
        elif direction == "2":
            result = value / meters_to_feet
            return f"{value} feet = {result:.2f} meters"
    elif conversion_type == "weight":
        if direction == "1":
            result = value * kg_to_pounds
            return f"{value} kg = {result:.2f} pounds"
        elif direction == "2":
            result = value / kg_to_pounds
            return f"{value} pounds = {result:.2f} kg"
    elif conversion_type == "volume":
        if direction == "1":
            result = value * liters_to_gallons
            return f"{value} liters = {result:.2f} gallons"
        elif direction == "2":
            result = value / liters_to_gallons
            return f"{value} gallons = {result:.2f} liters"

    raise ValueError("Invalid conversion type or direction")


def main():
    """Main program function handling user interaction"""
    print("Unit Conversion Program")
    print("Available conversions:")
    print("1. Length (meters <-> feet)")
    print("2. Weight (kilograms <-> pounds)")
    print("3. Volume (liters <-> gallons)")

    try:
        # Get conversion type
        conversion_type = input("\nChoose conversion type (length/weight/volume): ").lower()
        if conversion_type not in ["length", "weight", "volume"]:
            raise ValueError("Invalid conversion type")

        # Get conversion direction
        if conversion_type == "length":
            direction = input("Choose direction:\n1. Meters to Feet\n2. Feet to Meters\n> ")
        elif conversion_type == "weight":
            direction = input("Choose direction:\n1. Kilograms to Pounds\n2. Pounds to Kilograms\n> ")
        else:
            direction = input("Choose direction:\n1. Liters to Gallons\n2. Gallons to Liters\n> ")

        if direction not in ["1", "2"]:
            raise ValueError("Invalid direction choice")

        # Get value to convert
        value = float(input("Enter value to convert: "))

        # Perform conversion and display result
        result = convert_units(conversion_type, direction, value)
        print("\nConversion Result:")
        print(result)

    except ValueError as e:
        print(f"Error: {str(e)}")
    except Exception as e:
        print(f"An unexpected error occurred: {str(e)}")


if __name__ == "__main__":
    main()

Unit Conversion Program
Available conversions:
1. Length (meters <-> feet)
2. Weight (kilograms <-> pounds)
3. Volume (liters <-> gallons)

Choose conversion type (length/weight/volume): volume
Choose direction:
1. Liters to Gallons
2. Gallons to Liters
> 2
Enter value to convert: 85

Conversion Result:
85.0 gallons = 321.76 liters


 Task- 2:
 Create a Python program that performs various mathematical operations on a list of numbers

In [ ]:
def sum(numbers):
    """
    Calculate the sum of a list of numbers using loop.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: Sum of numbers.
    """
    total = 0
    for num in numbers:
        total += num
    return total

def average(numbers):
    """
    Calculate the average of a list of numbers using loop.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: Average
    """
    total = 0
    count = 0
    for num in numbers:
        total += num
        count += 1
    return total / count if count > 0 else 0

def maximum(numbers):
    """
    Find the maximum number in a list using a for loop.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: Maximum number.
    """
    max_value = numbers[0]
    for num in numbers:
        if num > max_value:
            max_value = num
    return max_value

def minimum(numbers):
    """
    Find the minimum number in a list using a for loop.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: Minimum number.
    """
    min_value = numbers[0]
    for num in numbers:
        if num < min_value:
            min_value = num
    return min_value

def main():
    """
    Main function to prompt user input and perform calculations.
    """
    print("Math Operations on a List of Numbers")
    print("Choose an operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    try:
        choice = int(input("Enter your choice (1/2/3/4): "))
        if choice not in [1, 2, 3, 4]:
            print("Invalid choice! Please select a valid option.")
            return

        numbers = input("Enter numbers separated by spaces: ").split()
        numbers = [float(num) for num in numbers]

        if not numbers:
            print("Error: No numbers provided.")
            return

        if choice == 1:
            result = sum(numbers)
            operation = "Sum"
        elif choice == 2:
            result = average(numbers)
            operation = "Average"
        elif choice == 3:
            result = maximum(numbers)
            operation = "Maximum"
        else:
            result = minimum(numbers)
            operation = "Minimum"

        print(f"{operation} of given numbers: {result:.4f}")

    except ValueError:
        print("Invalid input! Please enter numeric values only.")


if __name__ == "__main__":
    main()


Math Operations on a List of Numbers
Choose an operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter your choice (1/2/3/4): 2
Enter numbers separated by spaces: 5 8 9 4 7
Average of given numbers: 6.6000


**4.2 Exercise on List Manipulation:**

1. Extract Every Other Element

In [ ]:
def extract_every_other(lst):
    """
    Extracts every other element from a list, starting from the first element.

    Args:
        lst (list): The input list.

    Returns:
        list: A new list containing every other element.
    """
    result = []
    for i in range(0, len(lst), 2):
        result.append(lst[i])
    return result

print(extract_every_other([1, 2, 3, 4, 5, 6]))

[1, 3, 5]


2. Slice a Sublist

In [ ]:
def get_sublist(lst, start, end):
    """
    Returns a sublist from a given list, starting from a specified index and ending at another specified index.

    Args:
        lst (list): The input list.
        start (int): The starting index (inclusive).
        end (int): The ending index (inclusive).

    Returns:
        list: The sublist from start to end.
    """
    result = []
    for i in range(start, end + 1):
        result.append(lst[i])
    return result
print(get_sublist([1, 2, 3, 4, 5, 6], 2, 4))

[3, 4, 5]


3. Reverse a List Using Slicing

In [ ]:
def reverse_slicing_list(lst):
    """
    Reverses a list without using built-in functions.

    Args:
        lst (list): The input list.

    Returns:
        list: The reversed list.
    """
    result = []
    for i in range(len(lst) - 1, -1, -1):
        result.append(lst[i])
    return result

print(reverse_slicing_list([1, 2, 3, 4, 5]))

[5, 4, 3, 2, 1]


4. Remove the First and Last Elements

In [ ]:
def remove_first_last(lst):
    """
    Removes the first and last elements of a list and returns the resulting sublist.

    Args:
        lst (list): The input list.

    Returns:
        list: The sublist without the first and last elements.
    """
    result = []
    for i in range(1, len(lst) - 1):
        result.append(lst[i])
    return result

print(remove_first_last([1, 2, 3, 4, 5]))

[2, 3, 4]


5. Get the First n Elements

In [ ]:
def get_first_n(lst, n):
    """
    Extracts the first n elements from a list.

    Args:
        lst (list): The input list.
        n (int): The number of elements to extract.

    Returns:
        list: The first n elements of the list.
    """
    result = []
    for i in range(n):
        result.append(lst[i])
    return result

print(get_first_n([1, 2, 3, 4, 5], 3))

[1, 2, 3]


6. Extract Elements from the End

In [ ]:
def get_last_n(lst, n):
    """
    Extracts the last n elements of a list.

    Args:
        lst (list): The input list.
        n (int): The number of elements to extract from the end.

    Returns:
        list: The last n elements of the list.
    """
    result = []
    for i in range(len(lst) - n, len(lst)):
        result.append(lst[i])
    return result

print(get_last_n([1, 2, 3, 4, 5], 2))

[4, 5]


7. Extract Elements in Reverse Order

In [ ]:
def reverse_skip(lst):
    """
    Extracts a list of elements in reverse order starting from the second-to-last element,
    skipping one element in between.

    Args:
        lst (list): The input list.

    Returns:
        list: A new list containing every second element starting from the second-to-last,
              moving backward.
    """
    result = []
    for i in range(len(lst) - 2, -1, -2):
        result.append(lst[i])
    return result

print(reverse_skip([1, 2, 3, 4, 5, 6]))

[5, 3, 1]


4.3 Exercise on Nested List:

1. Flatten a Nested List

In [ ]:
def flatten(lst):
    """
    Flattens a nested list into a single-dimensional list.

    Args:
        lst (list): The input nested list.

    Returns:
        list: A flattened list.
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(flatten(item))
        else:
            result.append(item)
    return result

print(flatten([[1, 2], [3, 4], [5]]))

[1, 2, 3, 4, 5]


2. Accessing Nested List Elements

In [ ]:
def access_nested_element(lst, indices):
    """
    Extracts a specific element from a nested list given its indices.

    Args:
        lst (list): The input nested list.
        indices (list): A list of indices to access the element.

    Returns:
        The element at the specified indices.
    """
    current = lst
    for index in indices:
        current = current[index]
    return current

print(access_nested_element([[1, 2, 3], [4, 5, 6], [7, 8, 9]], [1, 2]))

6


3. Sum of All Elements in a Nested List

In [ ]:
def sum_nested(lst):
    """
    Calculates the sum of all elements in a nested list.

    Args:
        lst (list): The input nested list.

    Returns:
        int/float: The sum of all elements.
    """
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

print(sum_nested([[1, 2], [3, [4, 5]], 6]))

21


4. Remove Specific Element from a Nested List

In [ ]:
def remove_element(lst, elem):
    """
    Removes all occurrences of a specific element from a nested list.

    Args:
        lst (list): The input nested list.
        elem: The element to remove.

    Returns:
        list: The modified list with the element removed.
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        elif item != elem:
            result.append(item)
    return result
print(remove_element([[1, 2], [3, 2], [4, 5]], 2))

[[1], [3], [4, 5]]


5. Find the Maximum Element in a Nested List

In [ ]:
def find_max(lst):
    """
    Finds the maximum element in a nested list.

    Args:
        lst (list): The input nested list.

    Returns:
        int/float: The maximum element.
    """
    max_val = float('-inf')
    for item in lst:
        if isinstance(item, list):
            max_val = max(max_val, find_max(item))
        else:
            max_val = max(max_val, item)
    return max_val

print(find_max([[1, 2], [3, [4, 5]], 6]))

6


6. Count Occurrences of an Element in a Nested List

In [ ]:
def count_occurrences(lst, elem):
    """
    Counts how many times a specific element appears in a nested list.

    Args:
        lst (list): The input nested list.
        elem: The element to count.

    Returns:
        int: The number of occurrences of the element.
    """
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count
print(count_occurrences([[1, 2], [2, 3], [2, 4]], 2))

3


7. Flatten a List of Lists of Lists

In [ ]:
def deep_flatten(lst):
    """
    Flattens a deeply nested list into a single-dimensional list.

    Args:
        lst (list): The input deeply nested list.

    Returns:
        list: A flattened list.
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result

print(deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))

[1, 2, 3, 4, 5, 6, 7, 8]


8. Nested List Average

In [ ]:
def average_nested(lst):
    """
    Calculates the average of all elements in a nested list.

    Args:
        lst (list): The input nested list.

    Returns:
        float: The average of all elements.
    """
    def flatten(lst):
        result = []
        for item in lst:
            if isinstance(item, list):
                result.extend(flatten(item))
            else:
                result.append(item)
        return result

    flattened = flatten(lst)
    return sum(flattened) / len(flattened)
print(average_nested([[1, 2], [3, 4], [5, 6]]))

3.5


# **10.  To- Do- NumPy**

10.1  Basic Vector and Matrix Operation with Numpy.

Problem- 1: Array Creation:

In [ ]:
import numpy as np
emptyArray = np.empty((2, 2))
print("1. Empty Array:\n", emptyArray)

onesArray = np.ones((4, 2))
print("\n2. Ones Array:\n", onesArray)

fillArray = np.full((3, 3), 7)
print("\n3. Array filled with 7:\n", fillArray)

sampleArray = np.array([[1, 2, 3], [4, 5, 6]])
zeroslike_array = np.zeros_like(sampleArray)
print("\n4. Array of Zeros as sample array:\n", zeroslike_array)

oneslike_array = np.ones_like(sampleArray)
print("\n5. Array of Ones as sample array:\n", oneslike_array)

new_list = [1, 2, 3, 4]
numpyArray = np.array(new_list)
print("\n6. Converted List to NumPy Array:\n", numpyArray)


1. Empty Array:
 [[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]

2. Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Array filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Array of Zeros as sample array:
 [[0 0 0]
 [0 0 0]]

5. Array of Ones as sample array:
 [[1 1 1]
 [1 1 1]]

6. Converted List to NumPy Array:
 [1 2 3 4]


Problem- 2: Array Manipulation: Numerical Ranges and Array indexing

In [ ]:
arr10_to49 = np.arange(10, 50)
print("1. Array from 10 to 49:\n", arr10_to49)

matrix0_to8 = np.arange(9).reshape(3, 3)
print("\n2. 3x3 Matrix from 0 to 8:\n", matrix0_to8)

identityMatrix = np.eye(3)
print("\n3. Identity Matrix:\n", identityMatrix)

randomArray = np.random.random(30)
meanValue = np.mean(randomArray)
print("\n4. Mean of Random Array:\n", meanValue)

randomMatrix = np.random.random((10, 10))
minValue = np.min(randomMatrix)
maxValue = np.max(randomMatrix)
print("\n5.  Random Matrix Min & Max:\n", minValue, maxValue)

zeroArray = np.zeros(10)
zeroArray[4] = 1
print("\n6. Zero Array with 5th element replaced by 1:\n", zeroArray)

arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\n7. Reversed Array:\n", reversed_arr)

border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n8. 2D Array with 1 on Border and 0 Inside:\n", border_array)

checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n9. Checkerboard Pattern:\n", checkerboard)

1. Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 Matrix from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3. Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Mean of Random Array:
 0.5420310978557803

5.  Random Matrix Min & Max:
 0.007143355405369034 0.9900592703505442

6. Zero Array with 5th element replaced by 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

7. Reversed Array:
 [0 4 0 0 2 1]

8. 2D Array with 1 on Border and 0 Inside:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

9. Checkerboard Pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


 Problem- 3: Array Operations:

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

addition = x + y
print("1. Addition of x & y:\n", addition)

subtraction = x - y
print("\n2. Subtraction of x & y:\n", subtraction)

multiplication= x * 2
print("\n3. Multiplication of x by 2:\n", multiplication)

square = x ** 2
print("\n4. Square of each element in x:\n", square)

dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("\n5.")
print("\nDot product of v & w:\n", dot_vw)
print("\nDot product of x & v:\n", dot_xv)
print("\nDot product of x & y:\n", dot_xy)

concat_xy = np.concatenate((x, y), axis=0)
print("\n6. Concatenation of x and y along rows:\n", concat_xy)

concat_vw = np.vstack((v, w))
print("\nConcatenation of v and w along columns:\n", concat_vw)

try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("\n7.")
    print("\nConcatenation of x and v:\n", concat_xv)
except ValueError as e:
    print("\nError concatenating x and v:", e)

1. Addition of x & y:
 [[ 6  8]
 [10 13]]

2. Subtraction of x & y:
 [[-4 -4]
 [-4 -3]]

3. Multiplication of x by 2:
 [[ 2  4]
 [ 6 10]]

4. Square of each element in x:
 [[ 1  4]
 [ 9 25]]

5.

Dot product of v & w:
 219

Dot product of x & v:
 [29 77]

Dot product of x & y:
 [[19 22]
 [50 58]]

6. Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenation of v and w along columns:
 [[ 9 10]
 [11 12]]

Error concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


 Problem- 4: Matrix Operations:

In [ ]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

A_inverse = np.linalg.inv(A)
check = np.dot(A, A_inverse)
print("A * A⁻¹ = I:\n", check)

AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nMatrix AB:\n", AB)
print("\nMatrix BA:\n", BA)
if not np.array_equal(AB, BA):
    print("\nAB is NOT equal to BA")

AB_Transpose = np.transpose(AB)
BT_AT = np.dot(B.T, A.T)
print("\n(AB)ᵀ:\n", AB_Transpose)
print("\nBᵀ * Aᵀ:\n", BT_AT)
if np.array_equal(AB_Transpose, BT_AT):
    print("\n(AB)ᵀ is equal to Bᵀ * Aᵀ")

A_Matrix = np.array([[2, -3, 1],
                     [1, -1, 2],
                     [3, 1, -1]])

B_matrix = np.array([-1, -3, 9])

A_inverse = np.linalg.inv(A_Matrix)
solution = np.dot(A_inverse, B_matrix)
print("\nLinear Equations (x, y, z):\n", solution)

A * A⁻¹ = I:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

Matrix AB:
 [[23 13]
 [51 29]]

Matrix BA:
 [[36 44]
 [13 16]]

AB is NOT equal to BA

(AB)ᵀ:
 [[23 51]
 [13 29]]

Bᵀ * Aᵀ:
 [[23 51]
 [13 29]]

(AB)ᵀ is equal to Bᵀ * Aᵀ

Linear Equations (x, y, z):
 [ 2.  1. -2.]


10.2  Experiment: How Fast is Numpy?

In [ ]:
import time
import numpy as np

# Define sizes
Size = 1_000_000
matrix_size = 1000

# Initialize Python lists
list1 = [i for i in range(Size)]
list2 = [i for i in range(Size)]

# Initialize NumPy arrays
Array1 = np.arange(Size)
Array2 = np.arange(Size)

# 1. Element-wise Addition
start_time = time.perf_counter()
list_addition = [list1[i] + list2[i] for i in range(Size)]
list_addition_time = time.perf_counter() - start_time
print(f"Python Lists Addition Time: {list_addition_time:.5f} seconds")

start_time = time.perf_counter()
numpy_addition = Array1 + Array2
numpy_addition_time = time.perf_counter() - start_time
print(f"NumPy Arrays Addition Time: {numpy_addition_time:.5f} seconds")

# 2. Element-wise Multiplication
start_time = time.perf_counter()
list_multiplication = [list1[i] * list2[i] for i in range(Size)]
list_multiplication_time = time.perf_counter() - start_time
print(f"\nPython Lists Multiplication Time: {list_multiplication_time:.5f} seconds")

start_time = time.perf_counter()
numpy_multiplication = Array1 * Array2
numpy_multiplication_time = time.perf_counter() - start_time
print(f"NumPy Arrays Multiplication Time: {numpy_multiplication_time:.5f} seconds")

# 3. Dot Product
start_time = time.perf_counter()
dot_product = sum(list1[i] * list2[i] for i in range(Size))
list_dot_product_time = time.perf_counter() - start_time
print(f"\nPython Lists Dot Product Time: {list_dot_product_time:.5f} seconds")

start_time = time.perf_counter()
numpy_dot_product = np.dot(Array1, Array2)
numpy_dot_product_time = time.perf_counter() - start_time
print(f"NumPy Arrays Dot Product Time: {numpy_dot_product_time:.5f} seconds")

# 4. Matrix Multiplication
# Initialize Python matrices
list_matrix1 = [[j for j in range(matrix_size)] for i in range(matrix_size)]
list_matrix2 = [[j for j in range(matrix_size)] for i in range(matrix_size)]

# Initialize NumPy matrices
numpy_matrix1 = np.arange(matrix_size ** 2).reshape(matrix_size, matrix_size)
numpy_matrix2 = np.arange(matrix_size ** 2).reshape(matrix_size, matrix_size)

# Python matrix multiplication
start_time = time.perf_counter()
# Precompute the transposed matrix for efficiency
transposed_matrix2 = list(zip(*list_matrix2))
result_matrix = [[sum(a * b for a, b in zip(row, col)) for col in transposed_matrix2] for row in list_matrix1]
list_matrix_multiplication_time = time.perf_counter() - start_time
print(f"\nPython Lists Matrix Multiplication Time: {list_matrix_multiplication_time:.5f} seconds")

# NumPy matrix multiplication
start_time = time.perf_counter()
numpy_matrix_multiplication = np.matmul(numpy_matrix1, numpy_matrix2)
numpy_matrix_multiplication_time = time.perf_counter() - start_time
print(f"NumPy Arrays Matrix Multiplication Time: {numpy_matrix_multiplication_time:.5f} seconds")

Python Lists Addition Time: 0.16318 seconds
NumPy Arrays Addition Time: 0.00810 seconds

Python Lists Multiplication Time: 0.25107 seconds
NumPy Arrays Multiplication Time: 0.00982 seconds

Python Lists Dot Product Time: 0.44093 seconds
NumPy Arrays Dot Product Time: 0.00510 seconds

Python Lists Matrix Multiplication Time: 146.80280 seconds
NumPy Arrays Matrix Multiplication Time: 4.13889 seconds
